import type { Metadata } from "next";
import { montserrat } from "./fonts";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

// const bebas = Bebas_Neue({ subsets: ["latin"], weight: "400", style: ["normal"], variable: "--font-bebas"});

// const montserrat = Montserrat({ subsets: ["latin"], weight: ['400', '500'], style: ["italic"], variable: "--font-montserrat"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
